Implement solar display. Closes #17
icr-ctl/dencam pull request #22
Opened 2021-12-02 22:27 UTC by EliasMartinezJ

added a new page that will be used to display data received from the sunsaver device

2021-12-02 22:45 UTC, icr-ctl commented
Haven't reviewed the code, yet, but before I do, can you lint the code to PEP8.  I like to use flake8 which can be installed with

pip install flake8

and then you can run it on a given file that you changed thusly:

flake8 dencam.py

2021-12-09 18:08 UTC, tkswanson requested changes

2021-12-10 18:10 UTC, tkswanson commented on dencam/gui.py
> -        if self.state.value <= 1:
is state.value never 0?

2021-12-10 18:12 UTC, tkswanson approved these changes

2021-12-20 18:19 UTC, icr-ctl approved these changes

2021-12-20 18:19 UTC, merged