21 sunsaver logger
icr-ctl/dencam pull request #43
Opened 2022-02-02 06:04 UTC by EliasMartinezJ

closes issue #21

2022-02-04 22:54 UTC, tkswanson commented on dencam/sunsaver_log.py
> +        alarm_list = ["RTS open", "RTS shorted", "RTS disconnected",
variables like these lists can be declared outside of the function as global variables so the pi doesnt have to create them every time the function is called

2022-02-04 23:02 UTC, tkswanson requested changes
Just out of curiosity, is there are reason for having two scripts? mppt.py and sunsaver_log.py
Also, it doesn't look like this includes the font size change yet, correct?

2022-02-04 23:14 UTC, EliasMartinezJ commented
Was actually gonna ask, would I be able to merge these two scripts? And
just call the sole method that gets text for solar display without worrying
about the logger running? Since I call it at the bottom of the script.

Also right,  Im just about to push this new commit that fixes that .

I'll attach an image of how it looks now

On Fri, Feb 4, 2022, 3:02 PM Kyra Swanson ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Just out of curiosity, is there are reason for having two scripts? mppt.py
> and sunsaver_log.py
> Also, it doesn't look like this includes the font size change yet, correct?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/icr-ctl/dencam/pull/43#pullrequestreview-873661207>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWUW67XDJ55UWRR3QKVIZE3UZRLJPANCNFSM5NLEFVGQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-08 01:24 UTC, icr-ctl approved these changes
Rock on!

2022-02-08 01:46 UTC, merged